# Generated by Django 6.0.6 on 2026-06-19 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('energy', 'Energy'), ('food', 'Food'), ('goods', 'Goods')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('fun_fact', models.TextField(blank=True, help_text='Short contextual tip shown at log-time')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('energy', 'Energy'), ('food', 'Food'), ('goods', 'Goods')], max_length=50)),
                ('action', models.TextField()),
                ('potential_saving_kg', models.FloatField(help_text='Estimated kg CO2 saved per month')),
                ('effort', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], max_length=10)),
            ],
            options={
                'ordering': ['category', 'effort'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('energy', 'Energy'), ('food', 'Food'), ('goods', 'Goods')], max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('kg_co2_per_unit', models.FloatField()),
            ],
            options={
                'ordering': ['category', 'subcategory'],
                'unique_together': {('category', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('co2_kg', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.emissionfactor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kg_per_month', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
